config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  root "home#index"
  resources :quotes do
    resources :line_item_dates, except: [ :index, :show ] do
      resources :line_items, except: [ :index, :show ]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self }, target: "quotes" }
  # after_create_commit -> { broadcast_prepend_to "quotes" }
  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }
  broadcasts_to ->(quote) { [ quote.company, "quotes" ] }, inserts_by: :prepend

  def total_price
    line_items.sum(&:total_price)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = current_company.quotes.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = current_company.quotes.build(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_path, status: :see_other, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = current_company.quotes.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.expect(quote: [ :name ])
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_empty_state.html.erb
<div class="hidden p-5 text-center border border-dashed only:block">
  <p class="mb-5 text-xl font-bold text-black">
    You don't have any quotes yet!
  </p>
  <%= link_to "Add quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) }, class: "inline-block border text-sm rounded-md bg-primary-500 px-3 py-2 text-white hover:bg-primary-700" %>
</div>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, class: "border rounded shadow p-2 mb-3") do |form| %>
  <%= form_error_notification(quote) %>
  <div class="flex justify-between gap-2">
    <%= form.text_field :name, class: "flex-1 border border-gray-200 rounded p-1" %>
    <div class="flex gap-2">
      <%= link_to quotes_path, class: "block bg-gray-200 p-1 border rounded-md hover:bg-gray-300" do %>
        <span class="sr-only">Cancel</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9h13a5 5 0 0 1 0 10H7M3 9l4-4M3 9l4 4"/>
        </svg>
      <% end %>
      <%= form.button class: "bg-green-500 text-white p-1 border rounded-md hover:bg-green-600" do |text| %>
        <span class="sr-only"><%= text %></span>
        <svg class="w-6 h-6 text-white dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 11.917 9.724 16.5 19 7.5"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="flex items-center justify-between p-2 mb-3 bg-white rounded shadow">
    <%= link_to quote.name, quote, data: { turbo_frame: "_top" }, class: "text-primary-600" %>
    <div class="flex items-center gap-2">
      <%= button_to quote, method: :delete, class: "bg-gray-100 text-white p-1 border rounded-md hover:bg-gray-200" do %>
        <span class="sr-only">Delete</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
        </svg>
      <% end %>
      <%= link_to edit_quote_path(quote), class: "bg-gray-100 text-white p-1 border rounded-md hover:bg-gray-200" do %>
        <span class="sr-only">Edit</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/quotes/_total.html.erb
<footer class="fixed bottom-0 w-full p-3 font-bold bg-white shadow-lg">
  <div class="flex items-center justify-between max-w-screen-sm mx-auto">
    <div>Total:</div>
    <div><%= number_to_currency quote.total_price %></div>
  </div>
</footer>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/edit.html.erb
<% content_for :title, "Editing quote" %>
<h1>Editing quote</h1>
<%= turbo_frame_tag @quote do %>
  <%= render "form", quote: @quote %>
<% end %>
<br>
<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<% content_for :title, "Quotes" %>
<%= turbo_stream_from current_company,"quotes" %>
<div class="flex justify-between mb-5">
  <h1 class="text-3xl font-semibold">Quotes</h1>
  <%= link_to "New quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) }, class: "bg-primary-500 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-primary-700" %>
</div>
<%= turbo_frame_tag Quote.new %>
<%= turbo_frame_tag "quotes" do %>
  <%= render "quotes/empty_state" %>
  <%= render @quotes %>
<% end %>

app/views/quotes/new.html.erb
<% content_for :title, "New quote" %>
<h1>New quote</h1>
<%= turbo_frame_tag Quote.new do %>
  <%= render "form", quote: @quote %>
<% end %>
<br>
<div>
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/show.html.erb
<main class="px-3 mb-16 md:px-0">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="flex items-center justify-between mb-5">
    <h1 class="text-3xl font-semibold">
      <%= @quote.name %>
    </h1>
    <%= link_to "New date",
                new_quote_line_item_date_path(@quote),
                data: { turbo_frame: dom_id(LineItemDate.new) },
                class: "border bg-primary-500 text-white text-sm px-3 py-2 rounded-md" %>
  </div>
  <%= turbo_frame_tag LineItemDate.new %>
  <%= turbo_frame_tag "line_item_dates" do %>
    <%= render @line_item_dates, quote: @quote %>
  <% end %>
</main>
<%= content_for :footer do %>
  <%= turbo_frame_tag dom_id(@quote, :total) do %>
    <%= render "quotes/total", quote: @quote %>
  <% end %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.update @quote, partial: "quotes/quote", locals: { quote: @quote } %>
<%= render_turbo_stream_flash_messages %>