config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  root "home#index"
  resources :quotes do
    resources :line_item_dates, except: [ :index, :show ] do
      resources :line_items, except: [ :index, :show ]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<main class="text-center">
  <h1 class="mb-3 text-2xl font-bold">Quote editor</h1>
  <p class="mb-5">A blazing fast quote editor built with Hotwire</p>
  <% if Current.session %>
    <%= link_to "View quotes", quotes_path, class: "border rounded-md bg-primary-600 text-white p-2" %>
  <% else %>
    <%= link_to "Sign in", sign_in_path, class: "border rounded-md bg-primary-600 text-white p-2" %>
  <% end %>
</main>