config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  root "home#index"
  resources :quotes do
    resources :line_item_dates, except: [ :index, :show ] do
      resources :line_items, except: [ :index, :show ]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  delegate :quote, to: :line_item_date

  def total_price
    quantity * unit_price
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = @line_item_date.line_items.build
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = @line_item_date.line_items.build(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
        format.turbo_stream { flash.now[:notice] = "Item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
        format.turbo_stream { flash.now[:notice] = "Item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_path, status: :see_other, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { flash.now[:notice] = "Item was successfully destroyed." }
    end
  end

  private
  def set_quote
    @quote = current_company.quotes.find(params[:quote_id])
  end

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:line_item_date_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def line_item_params
    params.expect(line_item: %i[ line_item_date_id name description quantity unit_price ])
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for([quote, line_item_date, line_item], html: { class: "mb-3 bg-white shadow p-1 rounded" }) do |form| %>
  <%= form_error_notification(line_item) %>
  <div class="flex flex-wrap items-start gap-2">
    <%= form.text_field :name, placeholder: "Name", class: "border border-gray-200 rounded flex-1 p-1" %>
    <%= form.number_field :quantity, placeholder: "Quantity", class: "border border-gray-200 rounded p-1 w-[6rem]" %>
    <%= form.text_field :unit_price, placeholder: "Price", class: "border border-gray-200 rounded p-1 w-[7rem]" %>
    <%= form.textarea :description, placeholder: "Short description of article (optional)", class: "border border-gray-200 rounded p-1 order-2 basis-full max-w-full" %>
    <div class="flex gap-2 w-[5rem]">
      <%= link_to quote_path(quote), class: "block bg-gray-200 p-1 border rounded-md hover:bg-gray-300" do %>
        <span class="sr-only">Cancel</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9h13a5 5 0 0 1 0 10H7M3 9l4-4M3 9l4 4"/>
        </svg>
      <% end %>
      <%= form.button class: "bg-green-500 text-white p-1 border rounded-md hover:bg-green-600" do |text| %>
        <span class="sr-only"><%= text %></span>
        <svg class="w-6 h-6 text-white dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 11.917 9.724 16.5 19 7.5"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<%= turbo_frame_tag line_item do %>
  <div class="flex items-start gap-3 p-2 mb-1">
    <div class="flex-1">
      <%= line_item.name %>
      <div class="max-w-full flex-basis-100">
        <%= simple_format line_item.description %>
      </div>
    </div>
    <div class="w-[6rem]">
      <%= line_item.quantity %>
    </div>
    <div class="w-[6rem]">
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="flex order-2 gap-2 w-[5rem]">
      <%= button_to [quote, line_item_date, line_item], method: :delete, form: { data: { turbo_confirm: "Are you sure?" } },class: "bg-gray-100 text-white p-1 border rounded-md hover:bg-gray-200" do %>
        <span class="sr-only">Delete</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
        </svg>
      <% end %>
      <%= link_to [:edit, quote, line_item_date, line_item], class: "bg-gray-100 text-white p-1 border rounded-md hover:bg-gray-200" do %>
        <span class="sr-only">Edit</span>
        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/line_items/create.turbo_stream.erb
<%# Step 1: empty the Turbo Frame containing the form %>
<%= turbo_stream.update nested_dom_id(@line_item_date, LineItem.new), "" %>
<%# Step 2: append the created line item to the list %>
<%= turbo_stream.append nested_dom_id(@line_item_date, "line_items") do %>
  <%= render @line_item, quote: @quote, line_item_date: @line_item_date %>
<% end %>
<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item %>
<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/line_items/edit.html.erb
<% content_for :title, "Editing line item" %>
<h1>Editing line item</h1>
<%= turbo_frame_tag @line_item do %>
  <%= render "form", quote: @quote, line_item_date: @line_item_date,line_item: @line_item %>
<% end %>
<br>
<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Line items" %>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<% content_for :title, "New line item" %>
<h1>New line item</h1>
<%= turbo_frame_tag nested_dom_id(@line_item_date, LineItem.new) do %>
  <%= render "form", quote: @quote, line_item_date: @line_item_date, line_item: @line_item %>
<% end %>
<br>
<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.replace @line_item do %>
  <%= render @line_item, quote: @quote, line_item_date: @line_item_date %>
<% end %>
<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>
<%= render_turbo_stream_flash_messages %>